export const REQUEST_BABY_SKILLS = 'REQUEST_BABY_SKILLS';
export const RECEIVE_BABY_SKILLS = 'RECEIVE_BABY_SKILLS';
export const REQUEST_GAMES = 'REQUEST_GAMES';
export const RECEIVE_GAMES = 'RECEIVE_GAMES';
